import { type CompletedProject } from '@/components/showcase/project-showcase';

export const completedProjects: CompletedProject[] = [
  {
    id: '1',
    title: 'Smart Home Automation',
    description: 'IoT-based home automation system with voice control and mobile app integration.',
    studentName: 'Rahul Kumar',
    college: 'MIT World Peace University',
    category: 'IoT',
    imageUrl: '/images/projects/smart-home.jpg',
    completionDate: '2025-10-15',
    technologies: ['ESP32', 'Arduino', 'Node.js', 'Firebase'],
  },
  {
    id: '2',
    title: 'Automated Plant Watering',
    description: 'Smart irrigation system with soil moisture sensing and automated watering schedule.',
    studentName: 'Priya Sharma',
    college: 'VIT Pune',
    category: 'Agriculture',
    imageUrl: '/images/projects/plant-watering.jpg',
    completionDate: '2025-09-20',
    technologies: ['Arduino Uno', 'Sensors', 'IoT'],
  },
  {
    id: '3',
    title: 'Gesture Controlled Robot',
    description: 'Hand gesture-controlled robotic arm for precise object manipulation.',
    studentName: 'Aditya Patel',
    college: 'PICT Pune',
    category: 'Robotics',
    imageUrl: '/images/projects/gesture-robot.jpg',
    completionDate: '2025-08-30',
    technologies: ['Raspberry Pi', 'Python', 'Computer Vision'],
  },
  // {
  //   id: '4',
  //   title: 'Smart Parking System',
  //   description: 'Automated parking management with real-time slot availability tracking.',
  //   studentName: 'Sneha Desai',
  //   college: 'COEP Pune',
  //   category: 'IoT',
  //   imageUrl: '/images/projects/smart-parking.jpg',
  //   completionDate: '2025-11-01',
  //   technologies: ['Arduino Mega', 'RFID', 'Web Development'],
  // },
];

export const customerReviews = [
  {
    id: '1',
    name: 'Rahul Kumar',
    college: 'MIT World Peace University',
    rating: 5,
    comment: 'Excellent support throughout my project. The components were high quality and the documentation was very helpful. Completed my project well before the deadline!',
    date: '2025-10-20',
    projectTitle: 'Smart Home Automation',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    college: 'VIT Pune',
    rating: 5,
    comment: 'StudKits made my final year project journey smooth. Their troubleshooting support was exceptional when I faced issues.',
    date: '2025-09-25',
    projectTitle: 'Automated Plant Watering',
  },
  {
    id: '3',
    name: 'Aditya Patel',
    college: 'PICT Pune',
    rating: 4,
    comment: 'Great project kit with detailed instructions. The only minor issue was shipping time, but the quality made up for it.',
    date: '2025-09-05',
    projectTitle: 'Gesture Controlled Robot',
  },
  // {
  //   id: '4',
  //   name: 'Sneha Desai',
  //   college: 'COEP Pune',
  //   rating: 5,
  //   comment: 'The best decision I made for my project. Their custom solutions team helped me modify the project to match my requirements perfectly.',
  //   date: '2025-11-05',
  //   projectTitle: 'Smart Parking System',
  // },
];